- name: Backend Setup
  hosts: all
  become: true
  tasks:
    - name: Disable Default Version of NodeJS
      ansible.builtin.shell: dnf module disable nodejs -y

    - name: Enable NodeJS18 Version
      ansible.builtin.shell: dnf module enable nodejs:18 -y

    - name: Install NodeJS
      ansible.builtin.dnf:
        name: nodejs
        state: installed

    - name: Configure Backend Service
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: Adding Application User
      ansible.builtin.user:
        name: expense

    - name: Delete existing content
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Create Application Directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Downaload and extract App Content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/backend.zip
        dest: /app
        remote_src: yes

    - name: Downloading Application Dependencies
      community.general.npm:
        path: /app

    - name: Start Backend Service
      ansible.builtin.systemd_service:
          name: backend
          state: restarted
          enabled: yes

    - name: Install MySql Client
      ansible.builtin.dnf:
        name: mysqld
        state: installed

    - name: Install Python Library for Mysql
      ansible.builtin.dnf:
        name: python3-PyMySQL
        state: installed

    - name: Load Schema
      community.mysql.mysql_db:
        name: my_db
        state: import
        target: /app/schema/backend.sql
        login_user: root
        login_password: ExpenseApp@1












