format_version: 10
pipelines:
  deploy:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-c6c30de:
        git: https://github.com/kn-10/expense-ansible.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - test-stage:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            test-job:
              timeout: 0
              tasks:
                - exec:
                    command: ls
                    run_if: passed
