format_version: 10
pipelines:
  mysql:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      ansible:
        git: https://github.com/kn-10/expense-ansible.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - DEV:
          fetch_materials: true
          clean_workspace: false
          approval:
            type: manual
          jobs:
            deployment:
              timeout: 0
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments: ["-i", "mysl-dev.kdevops.online,", "-e", "ansible_user=centos", "-e", "ansible_password=DevOps321", "-e", "service_name=mysql", "-e", "env=dev", "expense.yml"]


      - QA:
          fetch_materials: true
          clean_workspace: false
          approval:
            type: manual
          jobs:
            deployment:
              timeout: 0
              tasks:
                - exec:
                    command: ls
                    arguments:
                      - -l
                      - -A

      - UAT:
          fetch_materials: true
          clean_workspace: false
          approval:
            type: manual
          jobs:
            deployment:
              timeout: 0
              tasks:
                - exec:
                    command: ls
                    arguments:
                      - -l
                      - -A

      - PROD:
          fetch_materials: true
          clean_workspace: false
          approval:
            type: manual
          jobs:
            deployment:
              timeout: 0
              tasks:
                - exec:
                    command: ls
                    arguments:
                      - -l
                      - -A